In [31]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import numpy as np

In [3]:
data =pd.read_csv("C:\\Users\\user\\Desktop\\DataScience with Python\\notes and materials\\Boston.csv")

In [4]:
data.head()

,crim,zn,indus,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [6]:
x =data.iloc[:,:12]
y =data.iloc[:,12]

In [7]:
x

,crim,zn,indus,nox,rm,age,dis,rad,tax,ptratio,black,lstat
0,0.00632,18.0,2.31,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [8]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [10]:
train_test_split(x,y,test_size=0.2 , random_state=0)

[         crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
 220   0.35809   0.0   6.20  0.507  6.951  88.5  2.8617    8  307     17.4
 71    0.15876   0.0  10.81  0.413  5.961  17.5  5.2873    4  305     19.2
 240   0.11329  30.0   4.93  0.428  6.897  54.3  6.3361    6  300     16.6
 6     0.08829  12.5   7.87  0.524  6.012  66.6  5.5605    5  311     15.2
 417  25.94060   0.0  18.10  0.679  5.304  89.1  1.6475   24  666     20.2
 ..        ...   ...    ...    ...    ...   ...     ...  ...  ...      ...
 323   0.28392   0.0   7.38  0.493  5.708  74.3  4.7211    5  287     19.6
 192   0.08664  45.0   3.44  0.437  7.178  26.3  6.4798    5  398     15.2
 117   0.15098   0.0  10.01  0.547  6.021  82.6  2.7474    6  432     17.8
 47    0.22927   0.0   6.91  0.448  6.030  85.5  5.6894    3  233     17.9
 172   0.13914   0.0   4.05  0.510  5.572  88.5  2.5961    5  296     16.6

       black  lstat
 220  391.70   9.71
 71   376.94   9.88
 240  391.25  11.38
 6    395.60  12.43
 417  127.36  26.64
 ..      ...    ...
 323  391.13  11.74
 192  390.49   2.87
 117  394.51  10.30
 47   392.74  18.80
 172  396.90  14.69

 [404 rows x 12 columns],
          crim    zn  indus    nox     rm    age     dis  rad  tax  ptratio  \
 329   0.06724   0.0   3.24  0.460  6.333   17.2  5.2146    4  430     16.9
 371   9.23230   0.0  18.10  0.631  6.216  100.0  1.1691   24  666     20.2
 219   0.11425   0.0  13.89  0.550  6.373   92.4  3.3633    5  276     16.4
 403  24.80170   0.0  18.10  0.693  5.349   96.0  1.7028   24  666     20.2
 78    0.05646   0.0  12.83  0.437  6.232   53.7  5.0141    5  398     18.7
 ..        ...   ...    ...    ...    ...    ...     ...  ...  ...      ...
 56    0.02055  85.0   0.74  0.410  6.383   35.7  9.1876    2  313     17.3
 455   4.75237   0.0  18.10  0.713  6.525   86.5  2.4358   24  666     20.2
 60    0.14932  25.0   5.13  0.453  5.741   66.2  7.2254    8  284     19.7
 213   0.14052   0.0  10.59  0.489  6.375   32.3  3.9454    4  277     18.6
 108   0.12802   0.0   8.56  0.520  6.474   97.1  2.4329    5  384     20.9

       black  lstat
 329  375.21   7.34
 371  366.15   9.53
 219  393.74  10.50
 403  396.90  19.77
 78   386.40  12.34
 ..      ...    ...
 56   396.90   5.77
 455   50.92  18.13
 60   395.11  13.15
 213  385.81   9.38
 108  395.24  12.27

 [102 rows x 12 columns],
 220    26.7
 71     21.7
 240    22.0
 6      22.9
 417    10.4
        ...
 323    18.5
 192    36.4
 117    19.2
 47     16.6
 172    23.1
 Name: medv, Length: 404, dtype: float64,
 329    22.6
 371    50.0
 219    23.0
 403     8.3
 78     21.2
        ...
 56     24.7
 455    14.1
 60     18.7
 213    28.1
 108    19.8
 Name: medv, Length: 102, dtype: float64]

In [11]:
x_train ,x_test ,y_train,y_test = train_test_split(x,y,test_size=0.2 , random_state=0)

In [12]:
x_train

,crim,zn,indus,nox,rm,age,dis,rad,tax,ptratio,black,lstat
220,0.35809,0.0,6.20,0.507,6.951,88.5,2.8617,8,307,17.4,391.70,9.71
71,0.15876,0.0,10.81,0.413,5.961,17.5,5.2873,4,305,19.2,376.94,9.88
240,0.11329,30.0,4.93,0.428,6.897,54.3,6.3361,6,300,16.6,391.25,11.38
6,0.08829,12.5,7.87,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.43
417,25.94060,0.0,18.10,0.679,5.304,89.1,1.6475,24,666,20.2,127.36,26.64
...,...,...,...,...,...,...,...,...,...,...,...,...
323,0.28392,0.0,7.38,0.493,5.708,74.3,4.7211,5,287,19.6,391.13,11.74
192,0.08664,45.0,3.44,0.437,7.178,26.3,6.4798,5,398,15.2,390.49,2.87
117,0.15098,0.0,10.01,0.547,6.021,82.6,2.7474,6,432,17.8,394.51,10.30
47,0.22927,0.0,6.91,0.448,6.030,85.5,5.6894,3,233,17.9,392.74,18.80
172,0.13914,0.0,4.05,0.510,5.572,88.5,2.5961,5,296,16.6,396.90,14.69

In [13]:
y_train

220    26.7
71     21.7
240    22.0
6      22.9
417    10.4
       ...
323    18.5
192    36.4
117    19.2
47     16.6
172    23.1
Name: medv, Length: 404, dtype: float64

In [14]:
x_test

,crim,zn,indus,nox,rm,age,dis,rad,tax,ptratio,black,lstat
329,0.06724,0.0,3.24,0.460,6.333,17.2,5.2146,4,430,16.9,375.21,7.34
371,9.23230,0.0,18.10,0.631,6.216,100.0,1.1691,24,666,20.2,366.15,9.53
219,0.11425,0.0,13.89,0.550,6.373,92.4,3.3633,5,276,16.4,393.74,10.50
403,24.80170,0.0,18.10,0.693,5.349,96.0,1.7028,24,666,20.2,396.90,19.77
78,0.05646,0.0,12.83,0.437,6.232,53.7,5.0141,5,398,18.7,386.40,12.34
...,...,...,...,...,...,...,...,...,...,...,...,...
56,0.02055,85.0,0.74,0.410,6.383,35.7,9.1876,2,313,17.3,396.90,5.77
455,4.75237,0.0,18.10,0.713,6.525,86.5,2.4358,24,666,20.2,50.92,18.13
60,0.14932,25.0,5.13,0.453,5.741,66.2,7.2254,8,284,19.7,395.11,13.15
213,0.14052,0.0,10.59,0.489,6.375,32.3,3.9454,4,277,18.6,385.81,9.38
108,0.12802,0.0,8.56,0.520,6.474,97.1,2.4329,5,384,20.9,395.24,12.27

In [15]:
y_test

329    22.6
371    50.0
219    23.0
403     8.3
78     21.2
       ...
56     24.7
455    14.1
60     18.7
213    28.1
108    19.8
Name: medv, Length: 102, dtype: float64

In [17]:
model = LinearRegression()

In [18]:
model.fit(x_train , y_train)

LinearRegression()

In [19]:
model.coef_

array([-1.25156811e-01,  4.48575121e-02,  2.01265385e-02, -1.62895522e+01,
        3.77366409e+00, -2.13185120e-03, -1.40611846e+00,  2.66835482e-01,
       -1.21692284e-02, -1.07660161e+00,  8.72533635e-03, -4.94425348e-01])

In [20]:
model.intercept_

np.float64(38.42706211257611)

In [23]:
model.score(x_train,y_train)

0.7690953567794605

In [27]:
y_pred =model.predict(x_test)

In [28]:
y_pred

array([24.80502192, 23.99207878, 27.41969853, 12.22521383, 21.54089609,
       19.30502294, 20.70506397, 21.495484  , 18.94490741, 19.79344825,
        4.75978975, 16.4343098 , 17.29081528,  5.64718895, 38.15388163,
       32.57410093, 22.70379646, 37.01957565, 31.05648795, 23.25919894,
       24.92104056, 24.99282993, 20.64411415, 30.56600209, 22.55400948,
       10.168633  , 17.70825917, 18.49796497, 35.77195417, 21.08709139,
       18.5413341 , 18.01931143, 20.03791552, 24.23016879, 29.34270932,
       17.14453905, 11.29301586, 22.46300599, 17.65919302, 15.69991479,
       26.46863641, 20.99738044, 22.2127374 , 15.78922293, 22.90368303,
       25.37354909, 20.366435  , 20.84948352, 10.27162372, 24.36650689,
       18.72120276, 17.3722084 , 24.74428345, 30.0915379 , 13.45683478,
       21.89909332, 20.77900494, 15.37903094, 13.76748828, 20.0599973 ,
       17.4889214 , 21.74283257, 33.13151667, 31.34567345, 17.8919454 ,
       32.84969957, 18.97445875, 20.02078883, 19.17996866, 23.05331047,
       23.09259692, 24.13099896, 30.78475572, 28.86073036, 26.19349382,
        5.30136643, 37.10722814, 23.97583859, 27.40127291, 19.36951504,
       28.80698404, 19.35352057, 19.155366  , 38.23739329, 39.66412153,
       23.81181303, 25.02422874, 15.84571573, 26.45375093, 16.91465087,
       15.53939105, 13.17184322, 24.67085986, 31.36491737, 22.29095528,
       20.28111902,  0.63998447, 25.37563907, 15.62819543, 18.03294772,
       25.49786202, 22.45773145])

In [29]:
 mean_squared_error(y_test,y_pred)

34.21225254753329

In [32]:
np.sqrt( mean_squared_error(y_test,y_pred))

np.float64(5.849124083786673)