In [5]:
import pandas as pd
import numpy as np

# Create a simple DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [23, 30, 28],
    "City": ["London", "Paris", "New York"]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

In [3]:
df

      Name  Age      City
0    Alice   23    London
1      Bob   30     Paris
2  Charlie   28  New York

In [9]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([11, 23, 35, 47, 59])

In [10]:
a.shape=(5,1)
b.shape=(5,1)

In [12]:
c = np.hstack((a,b))

In [14]:
pd.DataFrame(c,columns =["column A","column B"])

   column A  column B
0        10        11
1        20        23
2        30        35
3        40        47
4        50        59

In [19]:
data1 =pd.read_csv("C:\\Users\\user\\Desktop\\DataScience with Python\\notes and materials\\Boston.csv")

In [20]:
data1

,crim,zn,indus,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [32]:
# Read the iris sheet
data2 = pd.read_excel(
    r"C:\Users\user\Desktop\DataScience with Python\notes and materials\Excel Data.xlsx",
    sheet_name="iris"
)

In [36]:
# Read the marks sheet
data3= pd.read_excel(
    r"C:\Users\user\Desktop\DataScience with Python\notes and materials\Excel Data.xlsx",
    sheet_name="marks"
)

In [37]:
data2

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [38]:
data3

   ID  Marks
0   1     67
1   2     78
2   3     76
3   4     66
4   5     89

In [39]:
data1.head()

,crim,zn,indus,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [40]:
data3.tail()

   ID  Marks
0   1     67
1   2     78
2   3     76
3   4     66
4   5     89

In [41]:
data3.tail(2)

   ID  Marks
3   4     66
4   5     89